version: '3.8'

volumes:
  localstack-vol:


services:
  mlflow-db:
    image: postgres:14.3
    environment:
      POSTGRES_DB: mlflowdb
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"

  mlflow-server:
    build:
      context: ./src/dockerfiles/mlflow/
      dockerfile: Dockerfile
    container_name: mlflow_server
    environment:
      AWS_REGION: eu-west-3
      AWS_DEFAULT_REGION: eu-west-3
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: adminadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --backend-store-uri postgresql://mlflow:password@mlflow-db:5432/mlflowdb --default-artifact-root s3://test-bucket/

  minio:
    image: minio/minio:RELEASE.2022-05-19T18-20-59Z
    command: server /data --console-address ":9001"
    ports:
      - "9020:9000"
      - "9021:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
      MINIO_SITE_REGION: eu-west-3

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo sleep 30;
      sleep 30;
      /usr/bin/mc config host add myminio http://minio:9000 admin adminadmin;
      /usr/bin/mc mb myminio/test-bucket;
      exit 0;
      "
